---
title: "Devenir membre du CDC"
description: |
lang: fr
date: "2022-04-06"
---

L'Association Cercle Des Chercheurs (C.D.C) crée le 13 Octobre 2021 et reconnu par l'Etat par récépissé N000001270401 du 02 Février 2022.

Afin de permettre un meilleur renforcement du CDC, Le secrétariat exécutif national (SEN) lance une campagne d'adhésion des personnes physiques au CDC.

## Critères d'adhésion

Selon l'article 3 portant sur l'admission, les critères d'adhésion des personnes physiques sont :

-   Etre inscrit au moins au Master du système licence-Master-doctorat (LMD) ou aux DEA et DESS de l'ancien régime ;

-   Etre titulaire d'un Master, d'un DEA, d'un DESS ou d'un Doctorat ;

-   Etre un doctorant(e), un Chercheur, un Enseignant-Chercheur, un Chercheur associé et équivalent ;

-   Chaque membre doit faire preuve d'engagement, de solidarité et de respect envers les autres membres ;

-   Tous les membres obéissent aux principes d'égalité en droit et en devoir, et adhèrent au présent règlement intérieur

-   Etc.

## Modalités d'adhésion

Suite à une décision finale favorable du SEN, chaque personne doit payer les frais d'adhésion et la cotisation annuelle; la cotisation est payable en début de chaque année.
Pour participer aux activités et profiter des privilèges réservés aux membres actifs, les cotisations doivent être à jour; participer et s'impliquer activement dans la vie associative et aux activités de recherche entamée par l'association.

## Droits d'adhésion et cotisation

Conformément à l'article 5, portant sur les droits d'adhésion et de cotisation, les droits d'adhésion sont fixés à cinq mille (5000) francs CFA pour les personnes physiques.
Les cotisations annuelles sont fixées à cinq mille francs (5000) CFA par année pour les personnes physiques.

L'adhérant à droit à une carte de membres et sera intégré à un groupe whatsApp qui sera créé pour les adhérents uniquement.
Il bénéficie d'une réduction du cout lors des formations demandant des contributions financières et bien d'autres avantages issus de nos futures conventions avec des structures parténaires.

Les payements peuvent se faire physiquement auprès de la trésorière **Mademoiselle Ramatou KONATE** à l'**UFR-SEA** ou par **Orange money 76 20 99 15** et **Moov money 73 16 60 04**

Pour plus d'informations, contactez le Secrétaire chargé des Activités et de la Mobilisation des militants, **Monsieur Soumaila GORO au 76 06 14 19**.

## Inscription

Les demandes d'adhésion peuvent être formuler en ligne depuis ce [formulaire google](https://docs.google.com/forms/d/1nlgi6i0yfe4PR5u4pWK3Jk6CANUgaO94582fZkkVK8A/viewform?edit_requested=true "demande d'adhésion").

Télécharger le communiqué [ici](https://drive.google.com/file/d/1KwBtGYBImxC24bB-izSKm2CgwJb5G4-h/view?usp=sharing "Communiqué")
